name: Deploy to Dev
run-name: Deploy Dev (${{ github.sha }})
on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: iac-task-development
          IMAGE_TAG: backend_${{ github.sha }}
        run: |
          IMAGE=$REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE src/
          docker push $IMAGE
          echo image=$IMAGE >> "$GITHUB_OUTPUT"
      - name: Render ECS task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: backend-development
          container-name: backend-development
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy task to ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: backend-development
          cluster: instance_cluster