name: Deploy to Prod
run-name: Deploy Prod (${{ github.ref }})
on:
  workflow_call:
    inputs:
      ref:
        description: Git tag to deploy
        required: true
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: iac-task-production
          IMAGE_TAG: backend_${{ inputs.ref }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG src/
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG