name: Deploy to Dev
run-name: Deploy Dev (${{ github.sha }})
on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  run-deployment:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      ref: ${{ github.sha }}
      env: development
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}